### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AwesomeBros132** [IceM4nn/mirrorscript-v2#5]
Why do i keep getting this error? I've tried `python3 mirrorscript-v2.py` and still go `IndexError: list index out of range`
```
python3 mirrorscript-v2.py -https
#
# Mirrorscripts-v2 - By Hazmirul Afiq
# Automatically select the best Kali mirror and apply the configuration
# https://github.com/IceM4nn/mirrorscript-v2
# https://www.metahackers.pro/speed-kali-linux-update/
#

[-] Checking if 'apt-transport-https' package is installed.
[+] Getting mirror list ...
[+] Checking mirrors ...
[+] Finding the best latency
Traceback (most recent call last):
  File "/home/tagz/mirrorscript-v2/mirrorscript-v2.py", line 185, in <module>
    print("[+] Fastest mirror: " + str(sorted_mirrors[0]))
IndexError: list index out of range
```

**Comment by IceM4nn** [comment]
Try update the script with the new patch. See if the problem still persists. If it doesn't work, could you send the output with `--verbose` output?

**Comment by Tagz133** [comment]
Still isn't working.
Here is the verbose output.
```
#
# Mirrorscripts-v2 - By Hazmirul Afiq
# Automatically select the best Kali mirror and apply the configuration
# https://github.com/IceM4nn/mirrorscript-v2
# https://www.metahackers.pro/speed-kali-linux-update/
#

[+] Getting mirror list ...
[+] Found (15) lists of mirrors:
        - https://mirror.anigil.com/kali
        - https://mirror.karneval.cz/pub/linux/kali
        - https://ftp.acc.umu.se/mirror/kali.org/kali
        - https://mirror.pyratelan.org/kali
        - https://mirrors.dotsrc.org/kali
        - https://ftp.halifax.rwth-aachen.de/kali
        - https://ftp2.nluug.nl/os/Linux/distr/kali
        - https://ftp1.nluug.nl/os/Linux/distr/kali
        - https://archive-4.kali.org/kali
        - https://mirror.neostrada.nl/kali
        - https://mirror-1.truenetwork.ru/kali
        - https://mirror.anquan.cl/kali
        - https://kali.download/kali
        - https://mirror.lagoon.nc/kali
        - https://mirrors.ocf.berkeley.edu/kali

[+] Checking mirrors ...
[+] Finding the best latency
        - mirror.anigil.com              : [!] Unable to check mirror.anigil.com latency, potentially host block ICMP request.
        - mirror.pyratelan.org           : [!] Unable to check mirror.pyratelan.org latency, potentially host block ICMP request.
        - ftp.acc.umu.se                 : [!] Unable to check ftp.acc.umu.se latency, potentially host block ICMP request.
        - mirrors.dotsrc.org             : [!] Unable to check mirrors.dotsrc.org latency, potentially host block ICMP request.
        - ftp1.nluug.nl                  : [!] Unable to check ftp1.nluug.nl latency, potentially host block ICMP request.
        - mirror.lagoon.nc               : [!] Unable to check mirror.lagoon.nc latency, potentially host block ICMP request.
        - mirror.karneval.cz             : [!] Unable to check mirror.karneval.cz latency, potentially host block ICMP request.
        - mirror.neostrada.nl            : [!] Unable to check mirror.neostrada.nl latency, potentially host block ICMP request.
        - ftp2.nluug.nl                  : [!] Unable to check ftp2.nluug.nl latency, potentially host block ICMP request.
        - mirror.anquan.cl               : [!] Unable to check mirror.anquan.cl latency, potentially host block ICMP request.
        - archive-4.kali.org             : [!] Unable to check archive-4.kali.org latency, potentially host block ICMP request.
        - mirror-1.truenetwork.ru        : [!] Unable to check mirror-1.truenetwork.ru latency, potentially host block ICMP request.
        - ftp.halifax.rwth-aachen.de     : [!] Unable to check ftp.halifax.rwth-aachen.de latency, potentially host block ICMP request.
        - mirrors.ocf.berkeley.edu       : [!] Unable to check mirrors.ocf.berkeley.edu latency, potentially host block ICMP request.
        - kali.download                  : [!] Unable to check kali.download latency, potentially host block ICMP request.

Traceback (most recent call last):
  File "/home/tagz/mirrorscript-v2/mirrorscript-v2.py", line 185, in <module>
    print("[+] Fastest mirror: " + str(sorted_mirrors[0]))
IndexError: list index out of range

```

**Comment by IceM4nn** [comment]
Hmm it seems the problem is likely at your end. Is your DNS set up properly? Or can you ping any of the domain from the output above?

**Comment by Tagz133** [comment]
I can't ping any of the domains and I haven't edited my DNS or even checked it.

**Comment by IceM4nn** [comment]
Can you ping google.com? You have problem with your network connectivity. There's nothing wrong with the script.

**Comment by Tagz133** [comment]
I can access websites through a web browser with no problem but for some reason I can’t ping those websites.

**Comment by IceM4nn** [comment]
You may have a firewall which blocks ICMP ping request and/or response. The script is using ping latency check to determine which network mirror is closer to your location and sets the shortest latency as your apt sources.

**Comment by Tagz133** [comment]
Okay thank you for your help I appreciate it.

**Comment by IceM4nn** [comment]
No worries. Do find out what blocking that ICMP protocol either your local or external firewall, then allow the ICMP request/response to the Kali machine. This will allows you to perform a ping to external domain/IP. 

If you just want to set the good apt mirror, I found out that kali.download is the fastest at the time in my location. It may fast on your location too. Try updating the apt source manually. All the best.

**Comment by Tagz133** [comment]
Thank you and I will try to find out what is blocking the ICMP protocol.

**Comment by Tagz133** [comment]
Hey, I turned off the firewall and I even started a new Kali Linux image and still getting the same error.
